services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  chatbot:
    build: .
    restart: always
    environment:
      - DB_HOST=db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MODEL_ID=${MODEL_ID}
    ports:
      - "8501:8501"
    depends_on:
      - db
volumes:
  postgres_data:
